name=SumoDrive
version=0.0.2
author=UERJBotz
maintainer=UERJBotz, theo-al
sentence=Biblioteca para controle de motores em configuração de drive diferencial, com foco em robôs de mini sumô.
category=Device Control
url=https://github.com/UERJBotz/SumoDrive/
architectures=*
includes=SumoDrive.h
depends=
